# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Ligo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Ligo
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'Firebase/Crashlytics'
  pod 'Mixpanel-swift'
  
  pod 'SideMenu'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Messaging'
  
  pod 'EasyTipView', '~> 2.0.4'
  pod 'Firebase/Storage'
  
  
  target 'LigoTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'LigoUITests' do
    # Pods for testing
  end
  
end
